# Spring Boot App
spring.application.name=user-service

# gRPC Server Configuration
grpc.server.port=9090

# Enable gRPC reflection service, useful for debugging with tools like grpcurl
grpc.server.reflection-enabled=true
