# Spring Boot App
spring.application.name=user-service

# gRPC Server Configuration
grpc.server.port=9090

# Enable gRPC reflection service, useful for debugging with tools like grpcurl
grpc.server.reflection-enabled=true

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=user-service-group
app.kafka.topic.users=users.topic

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
app.rabbitmq.queue.users=users.queue
app.rabbitmq.exchange.users=users.exchange
app.rabbitmq.routingkey.users=users.routingkey
